language: python
addons:
  apt:
    packages:
    - xvfb
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &  
  - pip install -r requirements.txt
  - pip install nose
  #- pip install nose-exclude

script:
  - nosetests -v --ignore-files routes_test_file.py #Need to ignore import statements in these test files